ECS-3078 review certificates.md, the description of the certificate c…
input-output-hk/mithril pull request #1135
Opened 2023-08-04 10:51 UTC by NeilBurgess42

…hain.

## Content

Apply style guide to the document, suggest some changes to make it more concise.

## Pre-submit checklist

- Branch
  - [x] Tests are provided (if possible)
  - [x] Crates versions are updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] No clippy warnings in the CI
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested
- Documentation
  - [x] Update README file (if relevant)
  - [x] Update documentation website (if relevant)
  - [x] Add dev blog post (if relevant)

## Comments

## Issue(s)

Relates to #YYY or Closes #YYY

2023-08-04 11:44 UTC, olgahryniuk approved these changes

2023-08-04 11:45 UTC, olgahryniuk commented
@jpraynaud please review

2023-08-07 09:59 UTC, jpraynaud requested changes
Few minor changes before it's ready to be merged :slightly_smiling_face:

2023-08-07 09:59 UTC, jpraynaud commented on docs/root/mithril/mithril-protocol/certificates.md
> +Without the certificate, the stake distribution can't be trusted. A malicious actor could relatively easily create a fake stake distribution and use it to produce a valid multi-signature, which would
```suggestion
Without the certificate, the stake distribution can't be trusted. A malicious actor could relatively easily create a fake stake distribution and use it to produce a valid multi-signature, which would be embedded in a valid but non-genuine certificate. This certificate could be served by a dishonest Mithril aggregator node, leading an honest Mithril client to restore a non-genuine snapshot.  
```

2023-08-07 09:59 UTC, jpraynaud commented on docs/root/mithril/mithril-protocol/certificates.md
> +The first certificate in the certificate chain is known as the **genesis certificate**. Validating the stake distribution embedded in the genesis certificate is only possible by signing it with a pri
```suggestion
The first certificate in the certificate chain is known as the **genesis certificate**. Validating the stake distribution embedded in the genesis certificate is only possible by signing it with a private key linked to a widely accessible public key called the **genesis key**. The use of these specific keys ensures the integrity and security of the initial stake distribution and subsequent transitions within the blockchain network.
```

2023-08-07 09:59 UTC, jpraynaud commented on docs/root/mithril/mithril-protocol/certificates.md
> +* The parameter of the Mithril protocol (`k`, `m`, and `phi_f`)
```suggestion
* The parameters of the Mithril protocol (`k`, `m`, and `phi_f`)
```

2023-08-07 09:59 UTC, jpraynaud commented on docs/root/mithril/mithril-protocol/certificates.md
> +The **trigger** represents the instant at which a certificate should be created. It is combined with at least the associated **epoch** to create a [**beacon**](../../glossary.md#beacon) of the certif
```suggestion
The **trigger** represents the instant at which a certificate should be created. It is combined with at least the associated **epoch** to create a [**beacon**](../../glossary.md#beacon) of the certificate. In the current implementation of the Cardano node database snapshot, this trigger is a new [**immutable file number**](../../glossary.md#immutable-file-number). 
```

2023-08-07 09:59 UTC, jpraynaud commented on docs/root/mithril/mithril-protocol/certificates.md
> +* **Step 2**: Verify (or fail) that the `current_hash` of the `current_certificate` is valid by computing it and comparing it with the `hash`` field of the certificate
```suggestion
* **Step 2**: Verify (or fail) that the `current_hash` of the `current_certificate` is valid by computing it and comparing it with the `hash` field of the certificate
```

2023-08-07 09:59 UTC, jpraynaud commented on docs/root/mithril/mithril-protocol/certificates.md
> +    * **Step 5.1.1**: Verify (or fail) that the `previous_hash` of the `previous_certificate` is valid by computing it and comparing it with the `hash`` field of the certificate:
```suggestion
    * **Step 5.1.1**: Verify (or fail) that the `previous_hash` of the `previous_certificate` is valid by computing it and comparing it with the `hash` field of the certificate:
```

2023-08-07 09:59 UTC, jpraynaud commented on docs/root/mithril/mithril-protocol/certificates.md
> +    * **Step 5.2.1**: Verify (or fail) that the `previous_hash` of the `previous_certificate` is valid by computing it and comparing it with the `hash`` field of the certificate
```suggestion
    * **Step 5.2.1**: Verify (or fail) that the `previous_hash` of the `previous_certificate` is valid by computing it and comparing it with the `hash` field of the certificate
```

2023-08-07 12:51 UTC, jpraynaud approved these changes
LGTM :+1:

2023-08-08 13:03 UTC, merged