Enhance signer setup guide for SPO
input-output-hk/mithril pull request #1263
Opened 2023-09-26 14:42 UTC by jpraynaud

## Content
This PR includes some enhancements to the SPO guide to setup a Mithril signer (https://mithril.network/doc/manual/getting-started/run-signer-node):
- Add a process when updating the KES keys and OpCert
- Update the recommended listening port of the Mithril relay 
- Add configuration instructions for relay in front of multiple block producers

## Pre-submit checklist

- Branch
  - [ ] Commit sequence broadly makes sense
  - [ ] Key commits have useful messages
- PR
  - [ ] No clippy warnings in the CI
  - [ ] Self-reviewed the diff
  - [ ] Useful pull request description
  - [ ] Reviewer requested
- Documentation
  - [ ] Update documentation website (if relevant)

2023-09-26 16:30 UTC, Alenar approved these changes

2023-09-26 16:32 UTC, dlachaumepalo approved these changes

2023-09-27 08:55 UTC, olgahryniuk requested changes

2023-09-27 08:55 UTC, olgahryniuk commented on docs/website/root/manual/getting-started/run-signer-node.md
> +When the KES keys have expired, the Mithril signer is not able to register to the Mithril protocol.
```suggestion
When the KES keys expire, the Mithril signer is unable to register with the Mithril protocol.
```

2023-09-27 08:55 UTC, olgahryniuk commented on docs/website/root/manual/getting-started/run-signer-node.md
> +When you have rotated the KES keys on your Cardano block producer, we recommend the following upgrade procedure for your Mithril signer node:
```suggestion
After rotating the KES keys on your Cardano block producer, we recommend following this upgrade procedure for your Mithril signer node:
```

2023-09-27 08:55 UTC, olgahryniuk commented on docs/website/root/manual/getting-started/run-signer-node.md
> +2. Update the `OPERATIONAL_CERTIFICATE_PATH` entry of your environment file to reflect the location of the **new Operational certificate file**.
```suggestion
2. Update the `OPERATIONAL_CERTIFICATE_PATH` entry of your environment file to reflect the location of the **new operational certificate file**.
```

2023-09-27 11:54 UTC, dlachaumepalo approved these changes

2023-09-27 12:11 UTC, olgahryniuk approved these changes

2023-09-27 12:15 UTC, merged