Greg/1310/lower serialization
input-output-hk/mithril pull request #1333
Opened 2023-11-09 13:35 UTC by ghubertpalo

## Content
This PR adds a patch to reduce the serialization work on Certificate objects. Instead of embedding Signer instances (with their keys and certificate) it just owns party identifier and stake amount.

## Pre-submit checklist

- Branch
  - [X] Tests are provided (if possible)
  - [ ] Crates versions are updated (if relevant)
  - [X] Commit sequence broadly makes sense
  - [X] Key commits have useful messages
- PR
  - [X] No clippy warnings in the CI
  - [X] Self-reviewed the diff
  - [X] Useful pull request description
  - [X] Reviewer requested
- Documentation
  - [ ] Update README file (if relevant)
  - [ ] Update documentation website (if relevant)
  - [ ] Add dev blog post (if relevant)

## Comments
None

## Issue(s)
Relates to #1310

2023-11-09 14:16 UTC, Alenar commented on mithril-common/src/crypto_helper/tests_setup.rs
> +                        .collect();
It would be nice to migrate this code into a `fn stake_distribution_parties()` method on the `MithrilFixture`.

2023-11-09 14:16 UTC, Alenar commented on mithril-aggregator/src/database/provider/certificate.rs
> +        format!("select {projection} from certificate as c where {condition} order by ROWID desc")
Why does the changes from the soft limit reset commit are here ? You should rebase your PR on `main`.

2023-11-09 16:07 UTC, jpraynaud requested changes
There are few issues to fix before merging :slightly_smiling_face:

2023-11-09 16:49 UTC, dlachaumepalo commented on mithril-common/src/messages/message_parts/certificate_metadata.rs
> +            "This JSON is expected to be successfully parsed into a CertificateMetadataMessage instance.",
It's a tiny typo which is also present in `test_v1()`

```suggestion
            "This JSON is expected to be successfully parsed into a CertificateMetadataMessagePart instance.",
```

2023-11-09 16:52 UTC, dlachaumepalo commented on mithril-aggregator/src/database/provider/certificate.rs
>      /// The list of the active signers with their stakes and verification keys
```suggestion
    /// The list of the active signers with their stakes
```

2023-11-09 16:53 UTC, dlachaumepalo approved these changes
LGTM 🚀. Just few typos.

2023-11-10 10:23 UTC, jpraynaud approved these changes
LGTM :+1:

2023-11-10 12:33 UTC, merged