DATA_STORE_DIRECTORY
input-output-hk/mithril pull request #465
Opened 2022-08-30 23:36 UTC by SViksha

Added "DATA_STORE_DIRECTORY=/opt/mithril/mithril-signer/store" in environment file

2022-08-31 07:09 UTC, jpraynaud requested changes
Thanks @SViksha for finding out this issue :+1:

2022-08-31 07:09 UTC, jpraynaud commented on docs/root/manual/getting-started/run-signer-node.md
>    * `STAKE_STORE_DIRECTORY=/opt/mithril/mithril-signer/store/stake_db`: replace with the path to a folder where the **Mithril Signer** will store its data (`/opt/mithril/mithril-signer/store` e.g.)
```suggestion
```
This is not needed any more

2022-08-31 07:09 UTC, jpraynaud commented on docs/root/manual/getting-started/run-signer-node.md
>  STAKE_STORE_DIRECTORY=/opt/mithril/mithril-signer/store/stake_db
```suggestion
```
Same here

2022-08-31 07:09 UTC, jpraynaud commented on docs/root/manual/getting-started/run-signer-node.md
> +  * `DATA_STORE_DIRECTORY=/opt/mithril/mithril-signer/store`: replace with the path to a folder where the **Mithril Signer** will store its data (`/opt/mithril/mithril-signer/store` e.g.)
```suggestion
  * `DATA_STORES_DIRECTORY=/opt/mithril/mithril-signer/store`: replace with the path to a folder where the **Mithril Signer** will store its data (`/opt/mithril/mithril-signer/store` e.g.)
```

2022-08-31 07:09 UTC, jpraynaud commented on docs/root/manual/getting-started/run-signer-node.md
> +DATA_STORE_DIRECTORY=/opt/mithril/mithril-signer/store
```suggestion
DATA_STORES_DIRECTORY=/opt/mithril/mithril-signer/store
```

2022-09-01 14:14 UTC, jpraynaud commented
Hi @SViksha, are you ok if I apply the proposed modifications above and then merge the PR?

2022-09-01 17:12 UTC, SViksha commented
> Hi @SViksha, are you ok if I apply the proposed modifications above and then merge the PR?

sure, looks good to me

2022-09-01 17:21 UTC, jpraynaud approved these changes
LGTM :+1:

2022-09-01 17:21 UTC, merged